version: '3'
services:
  mlflow-server:
    build: ./mlflow-server
    container_name: mlflow-server
    volumes:
      - ./mlflow-server:/mlruns/
      - ./mlruns-artifacts:/mlruns-artifacts/
    ports:
      - "5000:5000"
    environment:
      TZ: Asia/Tokyo

  airflow-server:
    build: ./airflow-server
    container_name: airflow-server
    volumes:
      - ./airflow-server:/opt/airflow/
      - ./scrape:/opt/scrape/
      - ./mlproject:/opt/mlproject/
      - ./logs:/opt/logs/
      - ./data:/opt/data/
    ports:
      - "5005:5005"
    tty: true
    environment:
      TZ: Asia/Tokyo
