version: '3'
services:
  # python-env:
  #   build: .
  #   ports:
  #    - "5000:5000"
  mlflow-server:
    build: ./mlflow-server
    container_name: mlflow-server
    volumes:
      - ./mlflow-server:/mlruns/
      - ./mlruns-artifacts:/mlruns-artifacts/
    ports:
      - "5000:5000"